-- CreateEnum
CREATE TYPE "Industry" AS ENUM ('TEAM', 'BROADCASTERS_AND_OTT_PLATFORMS', 'PUBLISHERS', 'GAMING_OPERATORS', 'VIDEO_TECHNOLOGY_AND_AUTOMATED_CONTENT_CREATION', 'DIGITAL_PLATFORMS', 'FAN_DATA_AND_CRM_CONSULTING', 'MARKETING_AND_COMMUNITY', 'GAMING_AND_FAN_LOYALTY', 'MANAGEMENT', 'VIDEO_PRODUCTION', 'SPORTS_DATA_SOLUTIONS');

-- CreateEnum
CREATE TYPE "Solution" AS ENUM ('TEAM', 'BROADCASTERS_AND_OTT_PLATFORMS', 'PUBLISHERS', 'GAMING_OPERATORS', 'VIDEO_TECHNOLOGY_AND_AUTOMATED_CONTENT_CREATION', 'DIGITAL_PLATFORMS', 'FAN_DATA_AND_CRM_CONSULTING', 'MARKETING_AND_COMMUNITY', 'GAMING_AND_FAN_LOYALTY', 'MANAGEMENT', 'VIDEO_PRODUCTION', 'SPORTS_DATA_SOLUTIONS');

-- AlterTable
ALTER TABLE "customer_stories" ADD COLUMN     "industry" "Industry" NOT NULL DEFAULT 'TEAM',
ADD COLUMN     "solutions" "Solution"[] DEFAULT ARRAY[]::"Solution"[];
